### ISSUE TITLE
Moving cursor grabbing functionality into behavior along with a setting to enable it.

### ISSUE THREAD

**Issue by WillDonohoe** [ciampo/swiper-behavior#2]
On some of the projects we've integrated this, we've added functionality over the top on attached, which listens to touch start and end, and applies the grabbing cursor. This should be moved into the behavior to reduce duplication, with a setting to enable it.

**Comment by ciampo** [comment]
@WillDonohoe Could you submit a PR based on the code you previously wrote for this functionality?

**Comment by ciampo** [comment]
Closing this as per PR #3
